"""empty message

Revision ID: 1322a3851ea6
Revises: 19db67108c6c
Create Date: 2021-06-13 11:54:54.982024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1322a3851ea6'
down_revision = '19db67108c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'blog', ['blog_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'blog_id')
    # ### end Alembic commands ###
