"""empty message

Revision ID: 151865b08bec
Revises: fc9937a12a7a
Create Date: 2021-06-10 19:14:05.356417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151865b08bec'
down_revision = 'fc9937a12a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
