"""empty message

Revision ID: dc10278dfafb
Revises: 0b58f310bf58
Create Date: 2021-06-16 17:12:20.961998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc10278dfafb'
down_revision = '0b58f310bf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(length=32), nullable=False),
    sa.Column('mail', sa.VARCHAR(length=32), nullable=False),
    sa.Column('text', sa.VARCHAR(length=140), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
